Remove package gcc from arch linux provisioner
Building osquery fails if the [multilib] repository is enabled resulting
in a conflict between gcc and gcc-multilib:

$ pacman -S gcc
resolving dependencies...
looking for conflicting packages...
:: gcc and gcc-multilib are in conflict. Remove gcc-multilib? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: gcc and gcc-multilib are in conflict